// Package mcp resend_http_helpers.go holds the building blocks used by
// resend_http.go: input validation, synthetic envelope construction,
// dial-target resolution, scope checking, the resend pipeline factory, the
// upstream DialFunc, the one-shot run loop, and result formatting.
//
// These are split out so resend_http.go reads as a top-level orchestration
// while every step has a single responsibility documented in isolation.
package mcp

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"log/slog"
	"net"
	"net/url"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/google/uuid"

	"github.com/usk6666/yorishiro-proxy/internal/envelope"
	"github.com/usk6666/yorishiro-proxy/internal/exchange"
	"github.com/usk6666/yorishiro-proxy/internal/flow"
	"github.com/usk6666/yorishiro-proxy/internal/layer"
	"github.com/usk6666/yorishiro-proxy/internal/layer/http1"
	"github.com/usk6666/yorishiro-proxy/internal/pipeline"
	"github.com/usk6666/yorishiro-proxy/internal/pluginv2"
	httputilpkg "github.com/usk6666/yorishiro-proxy/internal/protocol/httputil"
	"github.com/usk6666/yorishiro-proxy/internal/session"
)

// resendHTTPSupportedProtocols lists the flow.Stream.Protocol values that
// resend_http accepts via flow_id. Non-HTTP protocols are rejected with an
// explicit pointer to the protocol-typed counterpart tool. The set mirrors
// the legacy resend tool's HTTP path plus SOCKS5 prefixes.
var resendHTTPSupportedProtocols = map[string]bool{
	"HTTP":          true,
	"HTTPS":         true,
	"HTTP/1.x":      true,
	"HTTP/1.1":      true,
	"HTTP/2":        true,
	"SOCKS5+HTTP":   true,
	"SOCKS5+HTTPS":  true,
	"SOCKS5+HTTP/2": true,
	// envelope.Protocol projection ("http") for streams created on the
	// new Layer stack.
	"http": true,
}

// validateOverrideHost validates that override_host is in host:port format.
func validateOverrideHost(host string) error {
	h, p, err := net.SplitHostPort(host)
	if err != nil {
		return fmt.Errorf("must be host:port format: %w", err)
	}
	if h == "" {
		return fmt.Errorf("host cannot be empty")
	}
	if p == "" {
		return fmt.Errorf("port cannot be empty")
	}
	return nil
}

// validateResendHTTPInput rejects malformed inputs at the schema boundary
// before any expensive lookups (flow store, dial) run. Header CR/LF guards,
// body-encoding parse, body_patch shape, and required-field rules live here.
func validateResendHTTPInput(input *resendHTTPInput) error {
	if input.FollowRedirects != nil && *input.FollowRedirects {
		return errors.New("follow_redirects is not supported by resend_http")
	}
	if err := validateHeaderKVList(input.Headers, "headers"); err != nil {
		return err
	}
	for i, p := range input.BodyPatches {
		if err := validateBodyPatch(p); err != nil {
			return fmt.Errorf("body_patches[%d]: %w", i, err)
		}
	}
	if input.OverrideHost != "" {
		if err := validateOverrideHost(input.OverrideHost); err != nil {
			return fmt.Errorf("invalid override_host %q: %w", input.OverrideHost, err)
		}
	}
	if input.FlowID == "" {
		return validateResendHTTPFromScratch(input)
	}
	return nil
}

// validateResendHTTPFromScratch checks that all required HTTPMessage fields
// are present when flow_id is omitted (the from-scratch path).
func validateResendHTTPFromScratch(input *resendHTTPInput) error {
	missing := []string{}
	if input.Method == "" {
		missing = append(missing, "method")
	}
	if input.Scheme == "" {
		missing = append(missing, "scheme")
	}
	if input.Authority == "" {
		missing = append(missing, "authority")
	}
	if input.Path == "" {
		missing = append(missing, "path")
	}
	if len(missing) > 0 {
		return fmt.Errorf("flow_id is empty; %s required", strings.Join(missing, ", "))
	}
	if input.Scheme != "http" && input.Scheme != "https" {
		return fmt.Errorf("unsupported scheme %q: only http and https are allowed", input.Scheme)
	}
	return nil
}

// buildResendHTTPEnvelope synthesises the *envelope.Envelope that the resend
// pipeline runs on. When flow_id is set, the original send Flow's
// fields fill any user-omitted slots; the user's overrides win on every
// supplied field. When flow_id is empty, every field comes from the user.
//
// StreamID is freshly generated so RecordStep creates a new Stream row;
// FlowID is generated by http1.BuildSendEnvelope. The envelope carries no
// Opaque (synthetic-send path inside http1.Channel.Send) and no Raw
// (Layer.Send re-encodes from Message at write time).
func (s *Server) buildResendHTTPEnvelope(ctx context.Context, input *resendHTTPInput) (*envelope.Envelope, error) {
	method := input.Method
	scheme := input.Scheme
	authority := input.Authority
	path := input.Path
	rawQuery := input.RawQuery
	var origHeaders []envelope.KeyValue
	var origBody []byte

	if input.FlowID != "" {
		stream, sendFlow, err := s.loadResendHTTPSendFlow(ctx, input.FlowID)
		if err != nil {
			return nil, err
		}
		if !resendHTTPSupportedProtocols[stream.Protocol] {
			return nil, fmt.Errorf("resend_http: protocol %q not supported by this tool — use resend_ws / resend_grpc / resend_raw for non-HTTP flows", stream.Protocol)
		}
		if method == "" {
			method = sendFlow.Method
		}
		if sendFlow.URL != nil {
			if scheme == "" {
				scheme = sendFlow.URL.Scheme
			}
			if authority == "" {
				authority = sendFlow.URL.Host
			}
			if path == "" {
				path = sendFlow.URL.Path
				if path == "" {
					path = "/"
				}
			}
			if rawQuery == "" {
				rawQuery = sendFlow.URL.RawQuery
			}
		}
		origHeaders = flowMapToKeyValues(sendFlow.Headers)
		origBody = sendFlow.Body
	}

	headers := origHeaders
	if input.Headers != nil {
		headers = headerKVsToKeyValues(input.Headers)
	}
	headers = ensureResendHTTPHostHeader(headers, authority)

	body, err := resolveResendHTTPBody(input, origBody)
	if err != nil {
		return nil, err
	}

	env := http1.BuildSendEnvelope(method, scheme, authority, path, rawQuery, headers, body)
	// BuildSendEnvelope does not set StreamID — RecordStep needs one to
	// open the new Stream row, so generate it here. RFC-001 streams are
	// per-resend (each invocation creates a fresh Stream + Flow pair).
	env.StreamID = uuid.NewString()
	return env, nil
}

// loadResendHTTPSendFlow fetches the Stream and its first send Flow for a
// given flow_id. Returns an explicit error when the store is unset or the
// stream has no send-direction flows.
func (s *Server) loadResendHTTPSendFlow(ctx context.Context, flowID string) (*flow.Stream, *flow.Flow, error) {
	if s.flowStore.store == nil {
		return nil, nil, errors.New("resend_http: flow store is not initialized")
	}
	stream, err := s.flowStore.store.GetStream(ctx, flowID)
	if err != nil {
		return nil, nil, fmt.Errorf("resend_http: get stream %s: %w", flowID, err)
	}
	flows, err := s.flowStore.store.GetFlows(ctx, flowID, flow.FlowListOptions{Direction: "send"})
	if err != nil {
		return nil, nil, fmt.Errorf("resend_http: get flows %s: %w", flowID, err)
	}
	if len(flows) == 0 {
		return nil, nil, fmt.Errorf("resend_http: stream %s has no send-direction flows", flowID)
	}
	return stream, flows[0], nil
}

// resolveResendHTTPBody decodes the user-supplied body or applies
// body_patches on top of the original Flow.Body, in that priority order.
// body_set distinguishes "omit body — keep original" from "override to empty
// body" so callers can deliberately blank a body without nil/empty
// ambiguity.
func resolveResendHTTPBody(input *resendHTTPInput, original []byte) ([]byte, error) {
	body := original
	if input.Body != "" || input.BodySet {
		decoded, err := decodeBodyEncoded(input.Body, input.BodyEncoding, "body")
		if err != nil {
			return nil, err
		}
		body = decoded
	}
	if len(input.BodyPatches) > 0 {
		patched, err := applyBodyPatches(body, input.BodyPatches)
		if err != nil {
			return nil, fmt.Errorf("body_patches: %w", err)
		}
		body = patched
	}
	return body, nil
}

// ensureResendHTTPHostHeader prepends a Host header derived from the
// authority field when the user-supplied or inherited header list does not
// already carry one (case-insensitive). HTTP/1.1 requires a Host header on
// every request; the synthetic-send wire path will not invent one, so a
// resend whose source flow recorded headers without a captured Host (a
// common shape in MITM Flow.Headers map projection) would otherwise produce
// a 400 from the upstream. Smuggling tests that need a missing or differing
// Host must override the headers list explicitly.
func ensureResendHTTPHostHeader(headers []envelope.KeyValue, authority string) []envelope.KeyValue {
	if authority == "" {
		return headers
	}
	for _, kv := range headers {
		if strings.EqualFold(kv.Name, "Host") {
			return headers
		}
	}
	out := make([]envelope.KeyValue, 0, len(headers)+1)
	out = append(out, envelope.KeyValue{Name: "Host", Value: authority})
	out = append(out, headers...)
	return out
}

// flowMapToKeyValues projects a flow.Flow.Headers multimap into an ordered
// envelope.KeyValue slice. The flow store is already lossy on inter-name
// order (map iteration is undefined); this helper preserves intra-name
// duplicate order as recorded. Header-list ordered overrides supplied via
// the input schema bypass this lossy projection.
func flowMapToKeyValues(headers map[string][]string) []envelope.KeyValue {
	if len(headers) == 0 {
		return nil
	}
	var out []envelope.KeyValue
	for name, values := range headers {
		for _, v := range values {
			out = append(out, envelope.KeyValue{Name: name, Value: v})
		}
	}
	return out
}

// resolveResendHTTPDial computes the upstream dial target, useTLS flag and
// SNI server name from the synthesised HTTPMessage and the optional
// override_host. override_host wins for the dial target while the request's
// :authority stays untouched (the smuggling / wrong-server-routing pattern).
func resolveResendHTTPDial(msg *envelope.HTTPMessage, overrideHost string) (addr string, useTLS bool, sni string, err error) {
	if msg.Authority == "" {
		return "", false, "", errors.New("resend_http: authority is empty")
	}
	useTLS = strings.EqualFold(msg.Scheme, "https")
	host := msg.Authority
	if h, _, splitErr := net.SplitHostPort(msg.Authority); splitErr == nil {
		host = h
	}
	sni = host
	port := ""
	if _, p, splitErr := net.SplitHostPort(msg.Authority); splitErr == nil {
		port = p
	}
	if port == "" {
		if useTLS {
			port = "443"
		} else {
			port = "80"
		}
	}
	addr = net.JoinHostPort(host, port)

	if overrideHost != "" {
		addr = overrideHost
		if h, _, splitErr := net.SplitHostPort(overrideHost); splitErr == nil {
			sni = h
		}
	}
	return addr, useTLS, sni, nil
}

// checkResendHTTPScope enforces TargetScope rules on both the canonical
// request URL and (when override_host is supplied) the override target. Both
// must pass; an override that bypasses scope is rejected even when the
// canonical authority is in-scope.
//
// Constructs the *url.URL directly from validated HTTPMessage fields rather
// than round-tripping via String → Parse: net/url's String() percent-encodes
// problematic Host bytes (whitespace, NUL, control chars) and the resulting
// "%XX" sequence in the host position is then rejected by Parse, silently
// swallowing the canonical-leg scope check (USK-672 review S-1, CWE-918).
// Falling through to the override leg only is not enough — the canonical
// authority is the path the dial actually takes when override_host is empty.
func (s *Server) checkResendHTTPScope(msg *envelope.HTTPMessage, addr, overrideHost string) error {
	canonical := resendHTTPRequestURL(msg)
	if err := s.checkTargetScopeURL(canonical); err != nil {
		return err
	}
	if overrideHost != "" {
		scheme := ""
		if strings.EqualFold(msg.Scheme, "https") {
			scheme = "https"
		}
		if err := s.checkTargetScopeAddr(scheme, addr); err != nil {
			return err
		}
	}
	return nil
}

// resendHTTPRequestURL composes the canonical *url.URL used for scope
// matching and safety filter input. Built directly from validated
// HTTPMessage fields without a String → Parse round-trip; see
// checkResendHTTPScope for the rationale.
func resendHTTPRequestURL(msg *envelope.HTTPMessage) *url.URL {
	return &url.URL{
		Scheme:   msg.Scheme,
		Host:     msg.Authority,
		Path:     msg.Path,
		RawQuery: msg.RawQuery,
	}
}

// keyValuesToExchangeKV adapts envelope.KeyValue (the new RFC-001 type) to
// exchange.KeyValue (the legacy type the SafetyEngine still consumes).
// Same-shape struct copy; no normalization.
func keyValuesToExchangeKV(kvs []envelope.KeyValue) []exchange.KeyValue {
	if len(kvs) == 0 {
		return nil
	}
	out := make([]exchange.KeyValue, len(kvs))
	for i, kv := range kvs {
		out[i] = exchange.KeyValue{Name: kv.Name, Value: kv.Value}
	}
	return out
}

// buildResendHTTPPipeline constructs the resend Pipeline:
//
//	PluginStepPost → RecordStep
//
// PluginStepPre and InterceptStep are intentionally absent (RFC §9.3 D1
// resend bypass). HostScope and Safety are handled at the handler level
// before the envelope reaches the pipeline; constructing them here would
// require engine wiring that the production data path does not yet plumb
// (those checks would no-op against the still-legacy production pipeline
// state). The wire encoder for HTTP is registered on a shared
// WireEncoderRegistry so PluginStepPost MessageOnly mutations regenerate
// env.Raw consistently with what RecordStep records as the modified
// variant's bytes.
func (s *Server) buildResendHTTPPipeline() *pipeline.Pipeline {
	encoders := pipeline.NewWireEncoderRegistry()
	encoders.Register(envelope.ProtocolHTTP, http1.EncodeWireBytes)

	steps := []pipeline.Step{
		pipeline.NewPluginStepPost(pluginEngineForResend(s), encoders, slog.Default()),
		pipeline.NewRecordStep(s.flowStore.store, slog.Default(), pipeline.WithWireEncoderRegistry(encoders)),
	}
	return pipeline.New(steps...)
}

// pluginEngineForResend returns the pluginv2.Engine to feed PluginStepPost.
// nil is acceptable — PluginStepPost no-ops when the engine is unset, which
// matches the test fixture (no plugins loaded → no hooks fire) and
// production until pluginv2 is wired into the live data path.
func pluginEngineForResend(s *Server) *pluginv2.Engine {
	if s.pluginEngine == nil {
		return nil
	}
	return s.pluginEngine.pluginv2
}

// buildResendHTTPDialFunc returns a session.DialFunc that dials addr,
// optionally upgrades to TLS via the configured TLSTransport, then wraps the
// connection in an http1 Layer in client (Receive) role. The returned
// Channel feeds the Job: Channel.Send writes the request, Channel.Next reads
// the response.
//
// useTLS is decided by the caller from msg.Scheme + override_host. SNI is
// the override host when provided so that wrong-server routing produces a
// matching ClientHello.
func buildResendHTTPDialFunc(transport httputilpkg.TLSTransport, addr string, useTLS bool, sni string) session.DialFunc {
	return func(ctx context.Context, _ *envelope.Envelope) (layer.Channel, error) {
		dialer := &net.Dialer{Timeout: defaultReplayTimeout}
		conn, err := dialer.DialContext(ctx, "tcp", addr)
		if err != nil {
			return nil, fmt.Errorf("dial %s: %w", addr, err)
		}
		if useTLS {
			tlsConn, _, tlsErr := upgradeResendTLS(ctx, transport, conn, sni)
			if tlsErr != nil {
				_ = conn.Close()
				return nil, tlsErr
			}
			conn = tlsConn
		}
		l := http1.New(conn, "", envelope.Receive)
		ch := <-l.Channels()
		return ch, nil
	}
}

// upgradeResendTLS performs the TLS handshake using the configured
// TLSTransport. A nil transport is rejected — the production wiring always
// supplies one (StandardTransport or UTLSTransport) and silently falling
// back to InsecureSkipVerify=true would defeat MITM diagnostics on the
// resend leg (review-gate S-2). Tests that exercise resend over plain HTTP
// take the useTLS=false path and never reach this function.
func upgradeResendTLS(ctx context.Context, transport httputilpkg.TLSTransport, conn net.Conn, sni string) (net.Conn, string, error) {
	if transport == nil {
		return nil, "", errors.New("resend_http: TLS upstream requires a configured TLSTransport")
	}
	out, alpn, err := transport.TLSConnect(ctx, conn, sni)
	if err != nil {
		return nil, "", fmt.Errorf("tls handshake %s: %w", sni, err)
	}
	return out, alpn, nil
}

// runResendHTTP runs the one-shot send/receive cycle. It dials, runs the
// send envelope through the resend pipeline, writes the request, reads the
// response, ties the response envelope to the same StreamID + Sequence=1,
// runs it through the same pipeline, and returns the response envelope.
//
// If the pipeline drops or responds short-circuits the send, runResendHTTP
// returns the produced response envelope (or nil for Drop) without
// performing the network round-trip.
func runResendHTTP(ctx context.Context, env *envelope.Envelope, dial session.DialFunc, p *pipeline.Pipeline) (*envelope.Envelope, error) {
	if p == nil {
		return nil, errors.New("resend pipeline is nil")
	}

	sendEnv, action, custom := p.Run(ctx, env)
	switch action {
	case pipeline.Drop:
		return nil, errors.New("send envelope dropped by pipeline")
	case pipeline.Respond:
		// Custom response short-circuit. Tie the response to the send's
		// StreamID and record it so analysts see the synthetic reply
		// alongside the request.
		if custom == nil {
			return nil, errors.New("pipeline returned Respond with nil response envelope")
		}
		custom.StreamID = sendEnv.StreamID
		custom.Sequence = 1
		_, _, _ = p.Run(ctx, custom)
		return custom, nil
	}

	ch, err := dial(ctx, sendEnv)
	if err != nil {
		return nil, fmt.Errorf("dial: %w", err)
	}
	defer ch.Close()

	if err := ch.Send(ctx, sendEnv); err != nil {
		return nil, fmt.Errorf("upstream send: %w", err)
	}
	respEnv, err := ch.Next(ctx)
	if err != nil {
		return nil, fmt.Errorf("upstream receive: %w", err)
	}
	// http1.New(conn, "", envelope.Receive) yielded the upstream Channel
	// with an empty connID, so respEnv.StreamID is empty. Pin it to the
	// send envelope's StreamID so RecordStep's variant-snapshot machinery
	// records the receive Flow under the same Stream row.
	respEnv.StreamID = sendEnv.StreamID
	respEnv.Sequence = 1

	// Pipeline.Run on the response envelope is purely for RecordStep + any
	// post_pipeline plugin that wants to observe the response. Drop /
	// Respond on the receive side has no meaningful semantics here (the
	// response is already on the wire to us); discarding the action keeps
	// the resend tool's contract simple — caller always sees the upstream
	// reply, masking applied by formatResendHTTPResult.
	respEnv, _, _ = p.Run(ctx, respEnv)
	return respEnv, nil
}

// applyResendHTTPTag persists the user-supplied tag on the new Stream row
// after the pipeline-driven RecordStep has created it. RecordStep does not
// observe the tag (resend is the only path that surfaces it today), so this
// post-pipeline UpdateStream is the cleanest place to set it.
func (s *Server) applyResendHTTPTag(ctx context.Context, streamID, tag string) {
	update := flow.StreamUpdate{Tags: map[string]string{"tag": tag}}
	if err := s.flowStore.store.UpdateStream(ctx, streamID, update); err != nil {
		slog.WarnContext(ctx, "resend_http: tag update failed",
			"stream_id", streamID,
			"tag", tag,
			"error", err,
		)
	}
}

// formatResendHTTPResult turns the response envelope into the wire-shape MCP
// result. SafetyFilter output masking is applied to body and headers before
// they leave the proxy boundary; the unmasked variant is already on disk via
// RecordStep so analysts retain the raw evidence.
func (s *Server) formatResendHTTPResult(streamID string, respEnv *envelope.Envelope, tag string, duration time.Duration) *resendHTTPResult {
	result := &resendHTTPResult{
		StreamID:   streamID,
		DurationMs: duration.Milliseconds(),
		Tag:        tag,
	}
	if respEnv == nil {
		return result
	}
	msg, ok := respEnv.Message.(*envelope.HTTPMessage)
	if !ok {
		return result
	}
	result.StatusCode = msg.Status
	maskedBody := s.filterOutputBody(msg.Body)
	result.Body, result.BodyEncoding = encodeResendHTTPBody(maskedBody)
	result.Headers = filterResendHTTPHeaders(s, msg.Headers)
	return result
}

// encodeResendHTTPBody returns the body string and its declared encoding.
// Empty bodies report encoding "text" so result schemas stay consistent.
func encodeResendHTTPBody(body []byte) (string, string) {
	if len(body) == 0 {
		return "", "text"
	}
	if utf8.Valid(body) {
		return string(body), "text"
	}
	return base64.StdEncoding.EncodeToString(body), "base64"
}

// filterResendHTTPHeaders applies SafetyFilter output masking to headers
// while preserving order, casing, and duplicates. Uses the raw-headers code
// path so the canonicalisation done by net/http.Header.Add never touches
// our wire-fidelity output. The filter is order-preserving on the parser
// RawHeaders type, so a positional copy back to envelope.KeyValue is exact.
func filterResendHTTPHeaders(s *Server, kvs []envelope.KeyValue) []headerKV {
	if len(kvs) == 0 {
		return nil
	}
	rh := keyValuesToRawHeaders(keyValuesToExchangeKV(kvs))
	masked := s.filterOutputRawHeaders(rh)
	out := make([]headerKV, len(masked))
	for i, h := range masked {
		out[i] = headerKV{Name: h.Name, Value: h.Value}
	}
	return out
}
