package main

import (
	"fmt"
	"strings"
)

// renderBody produces the Markdown PR body from a plan. Pure function of the
// plan so it can be unit-tested without any I/O.
func renderBody(p Plan) string {
	var b strings.Builder

	fmt.Fprintf(&b, "## Dependabot security updates (minimum release age: %.0f days)\n\n", p.MinAgeDays)
	b.WriteString("Automated weekly PR.\n\n")
	b.WriteString("- **Go**: only fixes whose patched version has been public for at least ")
	fmt.Fprintf(&b, "%.0f days are applied; newer fixes are deferred to a later run.\n", p.MinAgeDays)
	b.WriteString("- **npm**: applied via `pnpm update`; the release-age window, Takumi Guard registry, and exclusions are enforced natively by `web/.npmrc`.\n\n")

	if len(p.GoAccepted) > 0 {
		b.WriteString("### Go — applied\n\n")
		b.WriteString("| Module | → Version | Severity | Age (days) | Advisory |\n")
		b.WriteString("|---|---|---|---|---|\n")
		for _, c := range p.GoAccepted {
			fmt.Fprintf(&b, "| `%s` | `%s` | %s | %.1f | %s |\n",
				c.Name, c.TargetVersion, severityLabel(c.Severity), c.AgeDays, advisoryLink(c))
		}
		b.WriteString("\n")
	}

	if len(p.NpmUpdate) > 0 {
		b.WriteString("### npm — updated (direct deps, age-gated by pnpm/.npmrc)\n\n")
		b.WriteString("`pnpm update --latest` was run for these; pnpm picked the newest version at least ")
		fmt.Fprintf(&b, "%.0f days old. If a fix is still too new, it is silently deferred until eligible.\n\n", p.MinAgeDays)
		b.WriteString("| Package | Fixed in (advisory) | Severity | Advisory |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, c := range p.NpmUpdate {
			fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s |\n",
				c.Name, c.TargetVersion, severityLabel(c.Severity), advisoryLink(c))
		}
		b.WriteString("\n")
	}

	if len(p.GoDeferred) > 0 {
		b.WriteString("### Go — deferred (not yet past minimum release age)\n\n")
		b.WriteString("These fixes exist but are still too new. They will be picked up automatically once eligible.\n\n")
		b.WriteString("| Module | → Version | Severity | Eligible at |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, c := range p.GoDeferred {
			fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s |\n",
				c.Name, c.TargetVersion, severityLabel(c.Severity), c.EligibleAt.UTC().Format("2006-01-02"))
		}
		b.WriteString("\n")
	}

	if len(p.NpmManual) > 0 {
		b.WriteString("### npm — needs manual review (transitive dependencies)\n\n")
		b.WriteString("Per this repo's supply-chain policy, transitive npm packages are not auto-overridden.\n\n")
		b.WriteString("| Package | Fixed in | Severity | Advisory |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, c := range p.NpmManual {
			fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s |\n",
				c.Name, c.TargetVersion, severityLabel(c.Severity), advisoryLink(c))
		}
		b.WriteString("\n")
	}

	if len(p.Errors) > 0 {
		b.WriteString("### Could not process\n\n")
		for _, e := range p.Errors {
			fmt.Fprintf(&b, "- %s\n", e)
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n_Generated by `.github/workflows/dependabot-security.yml` · verify CI is green before merging._\n")
	return b.String()
}

func severityLabel(s string) string {
	if s == "" {
		return "unknown"
	}
	return s
}

func advisoryLink(c Candidate) string {
	switch {
	case c.URL != "" && c.GHSA != "":
		return fmt.Sprintf("[%s](%s)", c.GHSA, c.URL)
	case c.GHSA != "":
		return c.GHSA
	case c.CVE != "":
		return c.CVE
	default:
		return "—"
	}
}
